"""Regular expression patterns for constraint and fact detection."""

_CONSTRAINT_PATTERNS = [
    r"\bmust\b",
    r"\brequired\b",
    r"\bneed to\b",
    r"\bshould not\b",
    r"\bmust not\b",
    r"\bnever\b",
    r"\bavoid\b",
    r"\bprohibited\b",
    r"\bnot allowed\b",
    r"\bclosed\b",
    r"\breservation\b",
    r"\bpermit\b",
    r"\bvisa\b",
    r"\bID\b",
    r"\bminimum\b",
    r"\bmaximum\b",
    r"\bcap\b",
    r"\bno (pets|drones|campfires|fires)\b",
    r"\bhours?\b",
    r"\bopen\b",
    r"\bseason(al)?\b",
    r"\bweather\b",
    r"\broad\b.*\bclosed\b",
]

_FACT_PATTERNS = [
    r"\b(?:\d{1,2}:\d{2})\b",
    r"\b(?:am|pm)\b",
    r"\b(?:mile|miles|mi|km|kilometer)\b",
    r"\b(?:hour|hours|hr|hrs)\b",
    r"\b(?:\$|usd|eur|₹)\b",
    r"\b(?:temperature|°F|°C)\b",
    r"\b(?:latitude|longitude)\b",
    r"\b(?:drive|driving)\s+time\b",
    r"\b(?:distance)\b",
    r"\b(?:address)\b",
]